sudo: required
dist: trusty
language: node_js
node_js:
- 7
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install
- ng build
script: docker build -t cloudsea/cloudsea-webportal .
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push cloudsea/cloudsea-webportal
notifications:
  slack:
    secure: Uw4KCWnsa0fGMe9ZMaSwD3hkV7nzZaA7bHh7RNlf54kIm1P1ojmZ4w1/oyjfOjYHp7kxHzKAP+FahTgc3NhlTbMDRUrlkCgWRfK9Jywf7LNmBDMOGMLNUdGDl0rF19VkpshBZUhjrBt3cwHY/o+L5vBPTfbe7cQ9A8HARSu2LXTZoTjMWhdwaZmkwbgAF3Qr5odYFFuAHjiR9nQTtGwkfbsZdvJ+ZrbQytKWjS6nRt9KDmgRf0nJqJawwl4lzJSm2hctOC4Ps9zY2SxvHVpyFWCufuUN0Vmye7mkx80fO9Uix+A55jiyozMVn5wK7cDdCl2t1NjRiot1wtNYZucRVmYZxK32BgMJnvz9zG2oYq+0jisCBjJuPeQ6xwHvk3Wh7EimMbtl+YQRCdOe5PIosGLv+fKPJR7n0kugdLQpwGnIHn0s8XJZ029EbM7EL2L9dLlFtzYh8xDST7iCy/cbo6KA23GQwWNNXDQH4feqwphM8RPt57+YHdegkZg0yHYzugcYyGGPoe4psIMvhCWJ4rkc20X8s1HeVJrWM0B14n8oQvt83ayb7c8W3FytHeVQoOLwNly87P/GLCQXvkMyxL8EsX14zfm9a5pnEECaN4hs9Fa9O8Gsn2tQYJUped3TMEr+T2M4USsFPKNn0wHJlS3PVmiwMVV/qbXfopmts9M=
env:
  global:
  - secure: LGVIWhlImWjf4d/VL9KyLv4Mbyd9LIxxnWi+sv/RLFkZQW6bOtuuN6edbRqb8BJ2joBbbltOM9fCzocZbKYpP1tN5t4sNgTcdbW6e6e2mIDMFcT2olEtdKbAdGtyA1XkLNoZttx0q4igC8VvA4qUXDaGI8IIrfI6Vy4i6h43ODwQyAqGBikSRR3eZ3oLHBpZ08WMrye80xB4s+wJcNXNrUV6rYiLAMqj4K1f3PEQCTVwXJLwVgDj5WqWBUWZJa6ZDyTGC+QuQg3McB38e9Z5JNwlk7HZeZm8sgAZxkM8Z5xv97dM06JEpl6Sl1Wr7/tXYEGNDe47rmrs5YMFGylI4P3ROJhw7mtSwY2SKXrpqgvnrZ3m4E542pOVJAyE0Maq7HsgTPDsz/w24nqzBk7/dmMw+wwpZkNTd+NIOVfVCrxLm+lRFDjsWkItJA/oj+5FGJA4YFN6nEDpP7CLmiVUZNTk0e4hadRk8E/nTdmHZUhJHJ/hAcZJjNc1xKeXRhJkMWU1FTDFrw3nYmE5kQeg7O1oC9TO0EcPpVNz8nhSaDwAvaDZW0sCUslznOxZRbjl8aUU51ojizw6fazryNJSe/TSb1IuHXF9cFUViUqyZlp2Yqya3U1CuH8JJvVa+SBBYBlm1OMWe1tGQll5/Yr81uk8GbLEJePbE2utsiQpLC0=
  - secure: yDIaLbyGPhqDOVIiScqpk/+fx0nD9utr6pleEj2iK6NDXbZdfJW2iTApK/BbvpiGOtJRm7dQFj6/vNwXYwa7cXs3LYJ2Cadl65kaibzUyvYYJagWFAp9B7328JJLbAnto2Ti/7HiHNrVm0PMVIW3/qhAU9am6YKGlOWTWtJRg2xt6XdNvESR8OqeKcnnVx/wZL49SCDXsf2gLDET+8oZeZrJZ43ZHip8sSb9JX/woOezqURsQHJ6bCScRN2mbLHpeIylOFmAvh6rrJpHyQkrPLcq+trZfgKbbKxXb7N6y819lefNQjXiEQX815Al0Z7/liz4DLH7EpFEDz6+GAp5LhhjFgBtGU4UMfCDbd0VvuRe0IC8OhjRPogD088tgxWuNtaY/gfW7PUsJn+fw8XkV/JzM4l2wes5Trm0okmZY2qll7krbBOXody4tgQL2OwZ15ErqdxLDMepmu/Ed6e+UROWrcn7eJyU5LxADubSlUpNR/ta2hEk41sk5riDNIin4as3vKhDOJgqF1yFa30choG/GNWO2/1Itqfgb0mMFpQ+eioK0BKE4nr/K0A/4SQW++OR4kqSyRSnDXWHfU4sDCOus7k60eFHQ2RGiM8o8GE40qrnAaZ7Ld8zDGaBdNZ1fncN2r5jccO9CzeStrOQB8L9MFMDvvV+mHfqw4Kie0o=
  - secure: xyc3KHYyVcqJmgks4+/InDn6Duk6C+HLptOZO3NFvEy+UwbGesqK1s75SkxNtVqK+sOiCGGkcng6yD23nVnYOnXy5XpjkrFev55EMPPycfBb7udWLhyS9I1wKOf/6Wsu8Whlav42Dv3Vzm5N7joSm0Whs4GveRh/Q7O8kwzMlYmNV1IDydzjjJnfvZaLSEzE76nweXe801stykLrXyu4vjj4zEBbhRKJsVvnOxGxSnCqt62LpDqtpv46ed2x+2SABOvjn+EIA6fpkiN/VPOtLN4/6+U1vj9GZBdZVwtADZBmJpvH6BMrjXVwDhdjKQvgATxTPHgZqYICe+7mY3GTpmwuCp/d5benrlfEIncHFET1gwZcfbBYuZOFWViPuhklGv4+JKNJOs1Etu+Cf9PFCVignXTP+CsHeZ1TXb/t36iZPPwtXrXkFLz7MN80m/irLLsavWE8JoZyrbu6/wgCiFkFVyfO6PRqP0tWu8Uip9QsD20YdWEIs7vkjJ3/P+NHyriKV27SZJABTfufO/BJXqKcnxYYxbPXhpK2Klhy4f4Wj2SbxgF3vx4kpodzXWrBXP8dJBsK/LbqGt77qvCvWmi6IFF4QmPVFyjSGMV8/auPU5RYw78RPLcZ+stshpQklPZ54xT584o79c4gBw4X6ijGzuIfAC7uI6cRU/1S65M=
